---
- name: Clonando MVs. Ovejas con dos interfaces. Debian
  hosts: localhost
  gather_facts: false

  vars_files:
    - alu0101225562ull.yaml

  vars:
    ssh_keys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQD4bhDNmUNkH/b9Ami9Ij6wdvcwcJWvGfx9oIxo50XQTUJ8a2ooIrjMnP0YjXVSXyArPa/eVxNBla/wnZw/ZZTJuAJH4M1wsDUPUKkKTQAW5cG3SmnAd9IiD+Y4Z0wef06C4uvtEsuJECQ+bKw56SDzRLsJkIeOGiYGDrs4R4z9A9BS0oiG/7p9a69c4KcT9P+PLXMO70nyNqNIgqxCrHqhLhn5i6svgiU7VLZNksar/gfobaiZmIFFU1obNpeMhFQhkV4VLmi4Mt/OBBLTf4GnqAIR7hi0cdRBuOSO4/fJGNSEyrnIhgTRi8IeZkQ0Q/6WRja6gaX6ExRcFFagSQOSJtNyVwApzmPlZJWVtmwY/GKziFVutmWdRlp8Mv9Z74skZz5lKEm8zy6H1HxjZva+69wPaeQlx0ck79CncccR/6Wu6AvHX20RINpElUSvK6I0qmZn71jcFgS6CQpQfCMmVOP7eoK+DeSAdpm6qEODtsOg/Xbl5yjckH5SaoNorxh0Z2xcM9KOn7LCQA2UbSOwkIEnNidn1GY3zIXwYC68BFxFc2nw1IkfRLifKdJGF4GMw3ouJ0JTlnOjpcPKL0LDAfgB1sV/By1OucmNMv9QZPpMGBrY8H9TkgheIEr2MQ2sdYaeTIan0ja0X+CqgSlET6Dab6gqD4l7ygIeZR7c/Q== usuario@ubuntu
# Usuario IaaS (cambiar vblanco por aluxxx...)

    ovirt_login: alu0101225562@ULL

# Nodos a crear (en este caso dos ovejas)

    prefix: AITS-Alejandro

# Nodos a crear (en este caso dos ovejas)

    nodes:
      - name: dev1

# Especifiquen aqui el perfil de la red privada
# que tienen asignada

    node_nics: 
      - name: nic2
        profile_name: DOCP2P-4021

# Tareas
# ------

  tasks:
    - name: Login to IaaS
      ovirt_auth:
        url: https://iaas.ull.es/ovirt-engine/api
        insecure: yes
        username: "{{ ovirt_login }}"
        password: "{{ ovirt_password }}"
        headers:
          filter: true

    - name: Create a VM
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        cluster: Cluster-Rojo
        name: "{{ prefix }}-{{ item.name }}"
        template: debian-10-sinred-cloudinit
        nics: "{{ node_nics }}"
        state: present
        wait: yes
      with_items: "{{ nodes }}"
    
    - name: Update VM via cloud-init
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        name: "{{ prefix }}-{{ item.name }}"
        state: running
        cloud_init_nics:
          - nic_name: ens3
            nic_boot_protocol: dhcp
            nic_on_boot: yes
        cloud_init:
          host_name: "{{ item.name }}"
          user_name: ansible

# Passwd generado con mkpasswd -m SHA-512 alumno2020
# La clave en claro es: alumno2020
          root_password: $6$3diC789eX$WZPkCdIrIm11cbZyhx/uwsydqgqEb1hsBvOXIF31ngjqxYhGyXMdaHZrwsf8vZHqEBoqPoXhWANPR/itAEU7l.

          authorized_ssh_keys: "{{ ssh_keys }}"
          custom_script: |
            write_files:
              - path: /etc/sudoers.d/ansible
                permissions: '0644'
                content: |
                  ansible ALL=(ALL) NOPASSWD:ALL
              - path: /tmp/saludos.txt
                permissions: '0644'
                content: |
                  "Que pasa pisha"
            runcmd:
              - sed -i '/AllowUsers/c\AllowUsers adminstic usuario soporteiass ansible hadoop' /etc/ssh/sshd_config
              - systemctl restart sshd
        wait: yes
      with_items: "{{ nodes }}"

    - name: Cleanup IaaS auth token
      ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent
